version: '3'

services:

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  # cs-auth-service:
  #   build: .
  #   env_file:
  #     - .env
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - redis
